name: CI
on: [push, pull_request]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-2022
          #- macos-10.15
        dc:
          - dmd-2.108.1
          - dmd-2.102.1
          - ldc-1.38.0
          - ldc-1.31.0
        arch:
          - x86_64
        clang:
          - 12.0.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      # Ruby puts this on the path which breaks ldc
      - name: Rename msys64/link.exe
        if: startsWith(matrix.os,'windows')
        shell: pwsh
        run: mv C:\msys64\usr\bin\link.exe C:\msys64\usr\bin\msys-link.exe

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/llvm
          key: cache-os:${{ matrix.os }}-clang:${{ matrix.clang }}

      - name: Setup D
        uses: dlang-community/setup-dlang@v1.4.0
        with:
          compiler: ${{ matrix.dc }}

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          llvm: ${{ matrix.clang }}

      - name: Run tests
        continue-on-error: ${{ contains(matrix.os, 'macos') }}
        run: dub test -q --build=unittest-cov --arch=${{ matrix.arch }}
        env:
          LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      - name: Build binary
        run: dub build -q --arch=${{ matrix.arch }}
        env:
          LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      - uses: codecov/codecov-action@v3.1.4
